import type { PublicStory } from "./types";

/**
 * Demo stories for the Phase 28 public shell, derived from the reviewed
 * Phase 16 clustering benchmark (intelligence/clustering/tests/fixtures/
 * story-clusters.json). The benchmark's expected partition — asserted by
 * test_cluster_benchmark — is 4 multi-article stories plus 8 single-article
 * stories (each `story: null` entry forms its own story), so all 12 appear
 * here with their real headlines, categories, districts, sources, languages,
 * and timestamps. Rendered only via `?demo=1` behind a visible notice; never
 * mixed into the live feed.
 *
 * `curated` mirrors plan §54 feed tiers: development, audit, large-protest
 * and economic-report stories are tier A/selected-B (true); routine crime,
 * routine politics and uncategorised sports are tier C/D (false).
 */
export const DEMO_STORIES: PublicStory[] = [
  {
    id: "metro-approval",
    curated: true,
    canonicalTitle: "Cabinet approves Patna Metro expansion",
    primaryCategory: "Infrastructure",
    eventType: "approval",
    districtNames: ["Patna"],
    articleCount: 5,
    sourceCount: 5,
    firstSeenAt: "2026-09-28T10:00:00+05:30",
    lastSeenAt: "2026-09-28T16:30:00+05:30",
    languages: ["EN", "HI"],
  },
  {
    id: "flood-relief",
    curated: true,
    canonicalTitle: "Relief camps house 40,000 in north Bihar",
    primaryCategory: "Environment",
    eventType: null,
    districtNames: ["Supaul", "Saharsa"],
    articleCount: 3,
    sourceCount: 3,
    firstSeenAt: "2026-09-27T18:00:00+05:30",
    lastSeenAt: "2026-09-28T09:00:00+05:30",
    languages: ["EN", "HI"],
  },
  {
    id: "bpsc-calendar",
    curated: true,
    canonicalTitle: "शिक्षक नियुक्ति परीक्षा कैलेंडर जारी",
    primaryCategory: "Education",
    eventType: "announcement",
    districtNames: [],
    articleCount: 3,
    sourceCount: 3,
    firstSeenAt: "2026-09-27T18:00:00+05:30",
    lastSeenAt: "2026-09-28T07:00:00+05:30",
    languages: ["HI"],
  },
  {
    id: "bridge-collapse",
    curated: true,
    canonicalTitle: "Bridge collapses a year after construction",
    primaryCategory: "Infrastructure",
    eventType: null,
    districtNames: ["Saran"],
    articleCount: 2,
    sourceCount: 2,
    firstSeenAt: "2026-09-28T06:00:00+05:30",
    lastSeenAt: "2026-09-28T09:00:00+05:30",
    languages: ["EN"],
  },
  {
    id: "s-fares",
    curated: true,
    canonicalTitle: "Metro fares announced for first corridor",
    primaryCategory: "Infrastructure",
    eventType: "announcement",
    districtNames: ["Patna"],
    articleCount: 1,
    sourceCount: 1,
    firstSeenAt: "2026-09-28T18:00:00+05:30",
    lastSeenAt: "2026-09-28T18:00:00+05:30",
    languages: ["EN"],
  },
  {
    id: "s-robbery",
    curated: false,
    canonicalTitle: "Three arrested after Patna robbery",
    primaryCategory: "Governance",
    eventType: "crime",
    districtNames: ["Patna"],
    articleCount: 1,
    sourceCount: 1,
    firstSeenAt: "2026-09-28T11:00:00+05:30",
    lastSeenAt: "2026-09-28T11:00:00+05:30",
    languages: ["HI"],
  },
  {
    id: "s-rally",
    curated: false,
    canonicalTitle: "Minister attacks rival at Muzaffarpur rally",
    primaryCategory: null,
    eventType: null,
    districtNames: ["Muzaffarpur"],
    articleCount: 1,
    sourceCount: 1,
    firstSeenAt: "2026-09-28T17:00:00+05:30",
    lastSeenAt: "2026-09-28T17:00:00+05:30",
    languages: ["HI"],
  },
  {
    id: "s-cricket",
    curated: false,
    canonicalTitle: "State loses Ranji thriller",
    primaryCategory: null,
    eventType: null,
    districtNames: [],
    articleCount: 1,
    sourceCount: 1,
    firstSeenAt: "2026-09-28T19:00:00+05:30",
    lastSeenAt: "2026-09-28T19:00:00+05:30",
    languages: ["EN"],
  },
  {
    id: "s-cag",
    curated: true,
    canonicalTitle: "CAG flags road scheme irregularities",
    primaryCategory: "Economy",
    eventType: "audit",
    districtNames: ["Patna"],
    articleCount: 1,
    sourceCount: 1,
    firstSeenAt: "2026-09-26T11:00:00+05:30",
    lastSeenAt: "2026-09-26T11:00:00+05:30",
    languages: ["EN"],
  },
  {
    id: "s-protest",
    curated: true,
    canonicalTitle: "Teachers protest transfer policy",
    primaryCategory: "Education",
    eventType: "protest",
    districtNames: [],
    articleCount: 1,
    sourceCount: 1,
    firstSeenAt: "2026-09-28T13:00:00+05:30",
    lastSeenAt: "2026-09-28T13:00:00+05:30",
    languages: ["HI"],
  },
  {
    id: "s-gdp",
    curated: true,
    canonicalTitle: "State GDP growth pegged at 9.2 percent",
    primaryCategory: "Economy",
    eventType: "report",
    districtNames: [],
    articleCount: 1,
    sourceCount: 1,
    firstSeenAt: "2026-09-28T04:30:00+05:30",
    lastSeenAt: "2026-09-28T04:30:00+05:30",
    languages: ["EN"],
  },
  {
    id: "s-tender",
    curated: true,
    canonicalTitle: "Tenders invited for metro corridor works",
    primaryCategory: "Infrastructure",
    eventType: "tender",
    districtNames: ["Patna"],
    articleCount: 1,
    sourceCount: 1,
    firstSeenAt: "2026-10-28T10:00:00+05:30",
    lastSeenAt: "2026-10-28T10:00:00+05:30",
    languages: ["EN"],
  },
];
